### ISSUE TITLE
ETA for the  "Authentication and Authorization in ASP.NET Core Blazor " 

### ISSUE THREAD

**Issue by NickCodesDotNET** [KevinDockx/AuthNZinBlazor#1]
Hi Kevin. 
When will this updated course hit the pluralsight?  Not there yet. 

Thanks  
N -

**Comment by KevinDockx** [comment]
Hi Nick, 

the course is recorded but not edited yet.  It'll take a while, because after editing there's a few more review steps.  Writing the code and recording the course is just half of the process :)  I'm aiming for end of July.

**Comment by NickCodesDotNET** [comment]
Awesome! By the way, I am your long-term dedicated student and always looking forward to a new course.  Thank you for all your work. Good luck!

Nick-
